#pragma once

enum PacketIds{
    VOID_PACKET,
    ANNOUNCE_MESSAGE,
    USER_AUTHORIZE,
    USER_AUTHORIZE_RESPONSE,
    CHECK_BALANCE_REQUEST,
    CHECK_BALANCE_RESPONSE,
    USER_TRANSACTION_REQUEST,
    TEST_PACKET
};